version: "2"
services:
  redis:
    image: nick1chak/redis:0.1
    ports:
      - "9090:9090"
    networks:
      - webnet
  client:
    image: nick1chak/red_client:0.1
    ports:
      - "9090:9090"
    networks:
      - webnet
networks:
  webnet:
